queue_rules:
  - name: main-queue
    conditions:
      - base=main
    merge_method: squash

pull_request_rules:
  - name: queue jumic labeled PRs
    conditions:
      - base=main
      - "author=jumic"
      - "check-success=*"
      - "label=ready-to-merge"
      - "label!=do-not-merge"
    actions:
      queue:
        name: main-queue

  - name: queue external contributor PRs
    conditions:
      - base=main
      - "author!=jumic"
      - "author!=dependabot[bot]"
      - "#approved-reviews-by>=1"
      - "check-success=*"
      - "label!=do-not-merge"
    actions:
      queue:
        name: main-queue

  - name: queue dependabot PRs
    conditions:
      - base=main
      - "author=dependabot[bot]"
      - "check-success=*"
      - "label!=do-not-merge"
    actions:
      queue:
        name: main-queue
